// NOTE: This file a copy of ValidatorExtensionTests.Compare.Base.cs with all occurrences of 'xxx' replaced
// with 'XXX'.

using System;
using System.ComponentModel;
using Envoice.Conditions;
using Xunit;

namespace Envoice.Conditions.Tests.CompareTests
{
    public class CompareXXXTests
    {
        private static readonly XXX One = 1;
        private static readonly XXX Two = 2;
        private static readonly XXX Three = 3;
        private static readonly XXX Four = 4;
        private static readonly XXX Five = 5;

        #region IsXXXInRange

        [Fact]
        [Description("Calling IsInRange on XXX x with 'lower bound > x < upper bound' should fail.")]
        public void IsXXXInRangeTest01()
        {
            XXX a = One;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsInRange(Two, Four);
            });
        }

        [Fact]
        [Description("Calling IsInRange on XXX x with 'lower bound = x < upper bound' should pass.")]
        public void IsXXXInRangeTest02()
        {
            XXX a = Two;
            Condition.Requires(a).IsInRange(Two, Four);
        }

        [Fact]
        [Description("Calling IsInRange on XXX x with 'lower bound < x < upper bound' should pass.")]
        public void IsXXXInRangeTest03()
        {
            XXX a = Three;
            Condition.Requires(a).IsInRange(Two, Four);
        }

        [Fact]
        [Description("Calling IsInRange on XXX x with 'lower bound < x = upper bound' should pass.")]
        public void IsXXXInRangeTest04()
        {
            XXX a = Four;
            Condition.Requires(a).IsInRange(Two, Four);
        }

        [Fact]
        [Description("Calling IsInRange on XXX x with 'lower bound < x > upper bound' should fail.")]
        public void IsXXXInRangeTest05()
        {
            XXX a = Five;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsInRange(Two, Four);
            });
        }

        [Fact]
        [Description("Calling IsInRange on XXX x with conditionDescription should pass.")]
        public void IsXXXInRangeTest06()
        {
            XXX a = Four;
            Condition.Requires(a).IsInRange(Two, Four, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsInRange on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXInRangeTest07()
        {
            XXX a = Five;
            try
            {
                Condition.Requires(a, "a").IsInRange(Two, Four, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description("Calling IsInRange on XXX x with 'lower bound > x < upper bound' should succeed when exceptions are suppressed.")]
        public void IsXXXInRangeTest08()
        {
            XXX a = One;
            Condition.Requires(a).SuppressExceptionsForTest().IsInRange(Two, Four);
        }

        #endregion // IsXXXInRange

        #region IsXXXNotInRange

        [Fact]
        [Description("Calling IsNotInRange on XXX x with 'lower bound > x < upper bound' should pass.")]
        public void IsXXXNotInRangeTest01()
        {
            XXX a = One;
            Condition.Requires(a).IsNotInRange(Two, Four);
        }

        [Fact]
        [Description("Calling IsNotInRange on XXX x with 'lower bound = x < upper bound' should fail.")]
        public void IsXXXNotInRangeTest02()
        {
            XXX a = Two;

            Assert.Throws<ArgumentException>(() =>
            {
                Condition.Requires(a).IsNotInRange(Two, Four);
            });
        }

        [Fact]
        [Description("Calling IsNotInRange on XXX x with 'lower bound < x < upper bound' should fail.")]
        public void IsXXXNotInRangeTest03()
        {
            XXX a = Three;
            Assert.Throws<ArgumentException>(() =>
            {
                Condition.Requires(a).IsNotInRange(Two, Four);
            });
        }

        [Fact]
        [Description("Calling IsNotInRange on XXX x with 'lower bound < x = upper bound' should fail.")]
        public void IsXXXNotInRangeTest04()
        {
            XXX a = Four;

            Assert.Throws<ArgumentException>(() =>
            {
                Condition.Requires(a).IsNotInRange(Two, Four);
            });
        }

        [Fact]
        [Description("Calling IsNotInRange on XXX x with 'lower bound < x > upper bound' should pass.")]
        public void IsXXXNotInRangeTest05()
        {
            XXX a = Five;
            Condition.Requires(a).IsNotInRange(Two, Four);
        }

        [Fact]
        [Description("Calling IsNotInRange on XXX x with conditionDescription should pass.")]
        public void IsXXXNotInRangeTest06()
        {
            XXX a = Five;
            Condition.Requires(a).IsNotInRange(Two, Four, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsNotInRange on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXNotInRangeTest07()
        {
            XXX a = Four;
            try
            {
                Condition.Requires(a, "a").IsNotInRange(Two, Four, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description(
            "Calling IsNotInRange on XXX x with 'lower bound = x < upper bound' should succeed when exceptions are suppressed."
            )]
        public void IsXXXNotInRangeTest08()
        {
            XXX a = Two;
            Condition.Requires(a).SuppressExceptionsForTest().IsNotInRange(Two, Four);
        }

        #endregion // IsXXXNotInRange

        #region IsXXXGreaterThan

        [Fact]
        [Description("Calling IsGreaterThan on XXX x with 'lower bound < x' should fail.")]
        public void IsXXXGreaterThanTest01()
        {
            XXX a = One;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsGreaterThan(Two);
            });
        }

        [Fact]
        [Description("Calling IsGreaterThan on XXX x with 'lower bound = x' should fail.")]
        public void IsXXXGreaterThanTest02()
        {
            XXX a = Two;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsGreaterThan(Two);
            });
        }

        [Fact]
        [Description("Calling IsGreaterThan on XXX x with 'lower bound < x' should pass.")]
        public void IsXXXGreaterThanTest03()
        {
            XXX a = Three;
            Condition.Requires(a).IsGreaterThan(Two);
        }

        [Fact]
        [Description("Calling IsGreaterThan on XXX x with conditionDescription should pass.")]
        public void IsXXXGreaterThanTest04()
        {
            XXX a = Three;
            Condition.Requires(a).IsGreaterThan(Two, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsGreaterThan on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXGreaterThanTest05()
        {
            XXX a = Three;
            try
            {
                Condition.Requires(a, "a").IsGreaterThan(Three, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description("Calling IsGreaterThan on XXX x with 'lower bound < x' should succeed when exceptions are suppressed.")]
        public void IsXXXGreaterThanTest06()
        {
            XXX a = One;
            Condition.Requires(a).SuppressExceptionsForTest().IsGreaterThan(Two);
        }

        #endregion // IsXXXGreaterThan

        #region IsXXXNotGreaterThan

        [Fact]
        [Description("Calling IsNotGreaterThan on XXX x with 'x < upper bound' should pass.")]
        public void IsXXXNotGreaterThanTest01()
        {
            XXX a = One;
            Condition.Requires(a).IsNotGreaterThan(Two);
        }

        [Fact]
        [Description("Calling IsNotGreaterThan on XXX x with 'x = upper bound' should pass.")]
        public void IsXXXNotGreaterThanTest02()
        {
            XXX a = Two;
            Condition.Requires(a).IsNotGreaterThan(Two);
        }

        [Fact]
        [Description("Calling IsNotGreaterThan on XXX x with 'x > upper bound' should fail.")]
        public void IsXXXNotGreaterThanTest03()
        {
            XXX a = Three;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsNotGreaterThan(Two);
            });
        }

        [Fact]
        [Description("Calling IsNotGreaterThan on XXX x with conditionDescription should pass.")]
        public void IsXXXNotGreaterThanTest04()
        {
            XXX a = Two;
            Condition.Requires(a).IsNotGreaterThan(Two, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsNotGreaterThan on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXNotGreaterThanTest05()
        {
            XXX a = Three;
            try
            {
                Condition.Requires(a, "a").IsNotGreaterThan(Two, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description("Calling IsNotGreaterThan on XXX x with 'x > upper bound' should succeed when exceptions are suppressed.")]
        public void IsXXXNotGreaterThanTest06()
        {
            XXX a = Three;
            Condition.Requires(a).SuppressExceptionsForTest().IsNotGreaterThan(Two);
        }

        #endregion // IsXXXNotGreaterThan

        #region IsXXXGreaterOrEqual

        [Fact]
        [Description("Calling IsGreaterOrEqual on XXX x with 'lower bound > x' should fail.")]
        public void IsXXXGreaterOrEqualTest01()
        {
            XXX a = One;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsGreaterOrEqual(Two);
            });
        }

        [Fact]
        [Description("Calling IsGreaterOrEqual on XXX x with 'lower bound = x' should pass.")]
        public void IsXXXGreaterOrEqualTest02()
        {
            XXX a = Two;
            Condition.Requires(a).IsGreaterOrEqual(Two);
        }

        [Fact]
        [Description("Calling IsGreaterOrEqual on XXX x with 'lower bound < x' should pass.")]
        public void IsXXXGreaterOrEqualTest03()
        {
            XXX a = Three;
            Condition.Requires(a).IsGreaterOrEqual(Two);
        }

        [Fact]
        [Description("Calling IsGreaterOrEqual on XXX x with conditionDescription should pass.")]
        public void IsXXXGreaterOrEqualTest04()
        {
            XXX a = Three;
            Condition.Requires(a).IsGreaterOrEqual(Two, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsGreaterOrEqual on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXGreaterOrEqualTest05()
        {
            XXX a = One;
            try
            {
                Condition.Requires(a, "a").IsGreaterOrEqual(Two, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description("Calling IsGreaterOrEqual on XXX x with 'lower bound > x' should succeed when exceptions are suppressed.")]
        public void IsXXXGreaterOrEqualTest06()
        {
            XXX a = One;
            Condition.Requires(a).SuppressExceptionsForTest().IsGreaterOrEqual(Two);
        }

        #endregion // IsXXXGreaterOrEqual

        #region IsXXXNotGreaterOrEqual

        [Fact]
        [Description("Calling IsNotGreaterOrEqual on XXX x with 'x < upper bound' should pass.")]
        public void IsXXXNotGreaterOrEqualTest01()
        {
            XXX a = One;
            Condition.Requires(a).IsNotGreaterOrEqual(Two);
        }

        [Fact]
        [Description("Calling IsNotGreaterOrEqual on XXX x with 'x = upper bound' should fail.")]
        public void IsXXXNotGreaterOrEqualTest02()
        {
            XXX a = Two;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsNotGreaterOrEqual(Two);
            });
        }

        [Fact]
        [Description("Calling IsNotGreaterOrEqual on XXX x with 'x > upper bound' should fail.")]
        public void IsXXXNotGreaterOrEqualTest03()
        {
            XXX a = Three;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsNotGreaterOrEqual(Two);
            });
        }

        [Fact]
        [Description("Calling IsNotGreaterOrEqual on XXX x with conditionDescription should pass.")]
        public void IsXXXNotGreaterOrEqualTest04()
        {
            XXX a = One;
            Condition.Requires(a).IsNotGreaterOrEqual(Two, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsNotGreaterOrEqual on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXNotGreaterOrEqualTest05()
        {
            XXX a = Three;
            try
            {
                Condition.Requires(a, "a").IsNotGreaterOrEqual(Two, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description("Calling IsNotGreaterOrEqual on XXX x with 'x = upper bound' should succeed when exceptions are suppressed.")]
        public void IsXXXNotGreaterOrEqualTest06()
        {
            XXX a = Two;
            Condition.Requires(a).SuppressExceptionsForTest().IsNotGreaterOrEqual(Two);
        }

        #endregion // IsXXXNotGreaterOrEqual

        #region IsXXXLessThan

        [Fact]
        [Description("Calling IsLessThan on XXX x with 'x < upper bound' should pass.")]
        public void IsXXXLessThanTest01()
        {
            XXX a = One;
            Condition.Requires(a).IsLessThan(Two);
        }

        [Fact]
        [Description("Calling IsLessThan on XXX x with 'x = upper bound' should fail.")]
        public void IsXXXLessThanTest02()
        {
            XXX a = Two;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsLessThan(Two);
            });
        }

        [Fact]
        [Description("Calling IsLessThan on XXX x with 'x > upper bound' should fail.")]
        public void IsXXXLessThanTest03()
        {
            XXX a = Three;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsLessThan(Two);
            });
        }

        [Fact]
        [Description("Calling IsLessThan on XXX x with conditionDescription should pass.")]
        public void IsXXXLessThanTest04()
        {
            XXX a = Two;
            Condition.Requires(a).IsLessThan(Three, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsLessThan on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXLessThanTest05()
        {
            XXX a = Three;
            try
            {
                Condition.Requires(a, "a").IsLessThan(Two, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description("Calling IsLessThan on XXX x with 'x = upper bound' should succeed when exceptions are suppressed.")]
        public void IsXXXLessThanTest06()
        {
            XXX a = Two;
            Condition.Requires(a).SuppressExceptionsForTest().IsLessThan(Two);
        }

        #endregion // IsXXXLessThan

        #region IsXXXNotLessThan

        [Fact]
        [Description("Calling IsNotLessThan on XXX x with 'lower bound > x' should fail.")]
        public void IsXXXNotLessThanTest01()
        {
            XXX a = One;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsNotLessThan(Two);
            });
        }

        [Fact]
        [Description("Calling IsNotLessThan on XXX x with 'lower bound = x' should pass.")]
        public void IsXXXNotLessThanTest02()
        {
            XXX a = Two;
            Condition.Requires(a).IsNotLessThan(Two);
        }

        [Fact]
        [Description("Calling IsNotLessThan on XXX x with 'lower bound < x' should pass.")]
        public void IsXXXNotLessThanTest03()
        {
            XXX a = Three;
            Condition.Requires(a).IsNotLessThan(Two);
        }

        [Fact]
        [Description("Calling IsNotLessThan on XXX x with conditionDescription should pass.")]
        public void IsXXXNotLessThanTest04()
        {
            XXX a = Two;
            Condition.Requires(a).IsNotLessThan(Two, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsNotLessThan on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXNotLessThanTest05()
        {
            XXX a = Two;
            try
            {
                Condition.Requires(a, "a").IsNotLessThan(Three, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description("Calling IsNotLessThan on XXX x with 'lower bound > x' should succeed when exceptions are suppressed.")]
        public void IsXXXNotLessThanTest06()
        {
            XXX a = One;
            Condition.Requires(a).SuppressExceptionsForTest().IsNotLessThan(Two);
        }

        #endregion // IsXXXNotLessThan

        #region IsXXXLessOrEqual

        [Fact]
        [Description("Calling IsLessOrEqual on XXX x with 'x < upper bound' should pass.")]
        public void IsXXXLessOrEqualTest01()
        {
            XXX a = One;
            Condition.Requires(a).IsLessOrEqual(Two);
        }

        [Fact]
        [Description("Calling IsLessOrEqual on XXX x with 'x = upper bound' should pass.")]
        public void IsXXXLessOrEqualTest02()
        {
            XXX a = Two;
            Condition.Requires(a).IsLessOrEqual(Two);
        }

        [Fact]
        [Description("Calling IsLessOrEqual on XXX x with 'x > upper bound' should fail.")]
        public void IsXXXLessOrEqualTest03()
        {
            XXX a = Three;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsLessOrEqual(Two);
            });
        }

        [Fact]
        [Description("Calling IsLessOrEqual on XXX x with conditionDescription should pass.")]
        public void IsXXXLessOrEqualTest04()
        {
            XXX a = Two;
            Condition.Requires(a).IsLessOrEqual(Two, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsLessOrEqual on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXLessOrEqualTest05()
        {
            XXX a = Three;
            try
            {
                Condition.Requires(a, "a").IsLessOrEqual(Two, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description("Calling IsLessOrEqual on XXX x with 'x > upper bound' should succeed when exceptions are suppressed.")]
        public void IsXXXLessOrEqualTest06()
        {
            XXX a = Three;
            Condition.Requires(a).SuppressExceptionsForTest().IsLessOrEqual(Two);
        }

        #endregion // IsXXXLessOrEqual

        #region IsXXXNotLessOrEqual

        [Fact]
        [Description("Calling IsNotLessOrEqual on XXX x with 'lower bound > x' should fail.")]
        public void IsXXXNotLessOrEqualTest01()
        {
            XXX a = One;

            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsNotLessOrEqual(Two);
            });
        }

        [Fact]
        [Description("Calling IsNotLessOrEqual on XXX x with 'lower bound = x' should fail.")]
        public void IsXXXNotLessOrEqualTest02()
        {
            XXX a = Two;
            Assert.Throws<ArgumentOutOfRangeException>(() =>
            {
                Condition.Requires(a).IsNotLessOrEqual(Two);
            });
        }

        [Fact]
        [Description("Calling IsNotLessOrEqual on XXX x with 'lower bound < x' should pass.")]
        public void IsXXXNotLessOrEqualTest03()
        {
            XXX a = Three;
            Condition.Requires(a).IsNotLessOrEqual(Two);
        }

        [Fact]
        [Description("Calling IsNotLessOrEqual on XXX x with conditionDescription should pass.")]
        public void IsXXXNotLessOrEqualTest04()
        {
            XXX a = Three;
            Condition.Requires(a).IsNotLessOrEqual(Two, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsNotLessOrEqual on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXNotLessOrEqualTest05()
        {
            XXX a = Two;
            try
            {
                Condition.Requires(a, "a").IsNotLessOrEqual(Two, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description(
            "Calling IsNotLessOrEqual on XXX x with 'lower bound > x' should succeed when exceptions are suppressed."
            )]
        public void IsXXXNotLessOrEqualTest06()
        {
            XXX a = One;
            Condition.Requires(a).SuppressExceptionsForTest().IsNotLessOrEqual(Two);
        }

        #endregion // IsNotLessOrEqual

        #region IsXXXEqualTo

        [Fact]
        [Description("Calling IsEqualTo on XXX x with 'x < other' should fail.")]
        public void IsXXXEqualToTest01()
        {
            XXX a = One;

            Assert.Throws<ArgumentException>(() =>
            {
                Condition.Requires(a).IsEqualTo(Two);
            });
        }

        [Fact]
        [Description("Calling IsEqualTo on XXX x with 'x = other' should pass.")]
        public void IsXXXEqualToTest02()
        {
            XXX a = Two;
            Condition.Requires(a).IsEqualTo(Two);
        }

        [Fact]
        [Description("Calling IsEqualTo on XXX x with 'x > other' should fail.")]
        public void IsXXXEqualToTest03()
        {
            XXX a = Three;

            Assert.Throws<ArgumentException>(() =>
            {
                Condition.Requires(a).IsEqualTo(Two);
            });
        }

        [Fact]
        [Description("Calling IsEqualTo on XXX x with conditionDescription should pass.")]
        public void IsXXXEqualToTest04()
        {
            XXX a = Two;
            Condition.Requires(a).IsEqualTo(Two, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsEqualTo on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXEqualToTest05()
        {
            XXX a = Three;
            try
            {
                Condition.Requires(a, "a").IsEqualTo(Two, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description("Calling IsEqualTo on XXX x with 'x < other' should succeed when exceptions are suppressed.")]
        public void IsXXXEqualToTest06()
        {
            XXX a = One;
            Condition.Requires(a).SuppressExceptionsForTest().IsEqualTo(Two);
        }

        #endregion // IsXXXEqualTo

        #region IsXXXNotEqualTo

        [Fact]
        [Description("Calling IsNotEqualTo on XXX x with 'x < other' should pass.")]
        public void IsXXXNotEqualToTest01()
        {
            XXX a = One;
            Condition.Requires(a).IsNotEqualTo(Two);
        }

        [Fact]
        [Description("Calling IsNotEqualTo on XXX x with 'x = other' should fail.")]
        public void IsXXXNotEqualToTest02()
        {
            XXX a = Two;

            Assert.Throws<ArgumentException>(() =>
            {
                Condition.Requires(a).IsNotEqualTo(Two);
            });
        }

        [Fact]
        [Description("Calling IsNotEqualTo on XXX x with 'x > other' should pass.")]
        public void IsXXXNotEqualToTest03()
        {
            XXX a = Three;
            Condition.Requires(a).IsNotEqualTo(Two);
        }

        [Fact]
        [Description("Calling IsNotEqualTo on XXX x with conditionDescription should pass.")]
        public void IsXXXNotEqualToTest04()
        {
            XXX a = Three;
            Condition.Requires(a).IsNotEqualTo(Two, string.Empty);
        }

        [Fact]
        [Description("Calling a failing IsNotEqualTo on XXX should throw an Exception with an exception message that contains the given parameterized condition description argument.")]
        public void IsXXXNotEqualToTest05()
        {
            XXX a = Two;
            try
            {
                Condition.Requires(a, "a").IsNotEqualTo(Two, "abc {0} xyz");
                Assert.True(false);
            }
            catch (ArgumentException ex)
            {
                Assert.True(ex.Message.Contains("abc a xyz"));
            }
        }

        [Fact]
        [Description("Calling IsNotEqualTo on XXX x with 'x = other' should succeed when exceptions are suppressed.")        ]
        public void IsXXXNotEqualToTest06()
        {
            XXX a = Two;
            Condition.Requires(a).SuppressExceptionsForTest().IsNotEqualTo(Two);
        }

        #endregion // IsXXXNotEqualTo
    }
}
